/**
 * CONTRIBUTING — encabezado obligatorio para archivos de las bibliotecas canónicas.
 *
 * Cada archivo nuevo debe comenzar con:
 *   context, status, dependencies, ownership, version, limitations
 *
 * Reglas: no mezclar visión con capacidad implementada; no presentar simulaciones
 * como producción; no eliminar historia; no añadir secretos/PII/credenciales.
 */

export const FILE_STATUSES = ["draft", "alpha", "stable"] as const;
export type FileStatus = (typeof FILE_STATUSES)[number];

export interface CanonicalFileHeader {
  context: string;
  status: FileStatus;
  dependencies: readonly string[];
  ownership: string;
  version: string;
  limitations: readonly string[];
}

const SEMVER = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

export interface FileHeaderValidation {
  valid: boolean;
  missing: readonly string[];
  status?: FileStatus;
  version?: string;
}

/**
 * Valida el encabezado canónico. `draft | alpha | stable` únicamente.
 * Un archivo sin encabezado no cumple el gate de schema.
 */
export function validateFileHeader(header: Partial<CanonicalFileHeader>): FileHeaderValidation {
  const missing: string[] = [];
  if (!header.context?.trim()) missing.push("context");
  if (!header.status || !FILE_STATUSES.includes(header.status)) missing.push("status");
  if (!header.dependencies || header.dependencies.length === 0) missing.push("dependencies");
  if (!header.ownership?.trim()) missing.push("ownership");
  if (!header.version || !SEMVER.test(header.version)) missing.push("version");
  if (!header.limitations || header.limitations.length === 0) missing.push("limitations");
  return {
    valid: missing.length === 0,
    missing: Object.freeze(missing),
    status: header.status,
    version: header.version,
  };
}

export interface HumanApprovalDeclaration {
  approverId: string;
  evidenceId: string;
  approvedAt: string;
  signature: string;
}

export type HumanApprovalVerifier = (approval: HumanApprovalDeclaration) => boolean;

export interface HeaderScanResult {
  /** ¿el contenido declara explícitamente su estado auto-generado? */
  declaredAutoGenerated: boolean;
  /** Marcador declarado en texto; no prueba que la aprobación sea auténtica. */
  declaredHumanApproved: boolean;
  humanApprovalVerified: boolean;
  /** estado efectivo según transparencia radical. */
  effectiveState: FileStatus | "auto_generated";
}

/**
 * Los marcadores textuales no autentican aprobación humana. stable requiere
 * una declaración y un verificador de aprobación confiable conectado por el caller.
 */
export function scanTransparency(
  content: string,
  declaredStatus?: FileStatus,
  approval?: HumanApprovalDeclaration,
  verifyApproval?: HumanApprovalVerifier,
): HeaderScanResult {
  const declaredAutoGenerated = /\bstate:\s*(?:draft|auto_generated)\b/i.test(content) || /\bauto_generated\b/i.test(content);
  const declaredHumanApproved = /\bhuman[_-]?approved\b/i.test(content) || /\bhuman[_-]?authored\b/i.test(content);
  let humanApprovalVerified = false;
  if (approval && verifyApproval &&
      [approval.approverId, approval.evidenceId, approval.signature].every((value) => value.trim()) &&
      Number.isFinite(Date.parse(approval.approvedAt))) {
    try { humanApprovalVerified = verifyApproval(approval) === true; } catch { humanApprovalVerified = false; }
  }
  let effectiveState: FileStatus | "auto_generated";
  if (declaredStatus === "stable" && (!declaredHumanApproved || !humanApprovalVerified)) {
    effectiveState = declaredAutoGenerated ? "auto_generated" : "draft";
  } else if (humanApprovalVerified) {
    effectiveState = declaredStatus ?? "stable";
  } else if (declaredAutoGenerated) {
    effectiveState = "auto_generated";
  } else {
    effectiveState = declaredStatus ?? "draft";
  }
  return { declaredAutoGenerated, declaredHumanApproved, humanApprovalVerified, effectiveState };
}

/** Detecta credenciales/PII que las reglas de contribución prohíben. */
export function detectForbiddenContent(content: string): readonly string[] {
  const findings: string[] = [];
  if (/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(content)) findings.push("private_key");
  if (/\bAKIA[0-9A-Z]{16}\b/.test(content)) findings.push("aws_access_key");
  if (/\bBearer\s+[A-Za-z0-9._-]{20,}/.test(content)) findings.push("bearer_token");
  return Object.freeze(findings);
}
