/**
 * CONTRIBUTING — encabezado obligatorio para archivos de las bibliotecas canónicas.
 *
 * Cada archivo nuevo debe comenzar con:
 *   context, status, dependencies, ownership, version, limitations
 *
 * Reglas: no mezclar visión con capacidad implementada; no presentar simulaciones
 * como producción; no eliminar historia; no añadir secretos/PII/credenciales.
 */

export const FILE_STATUSES = ["draft", "alpha", "stable"] as const;
export type FileStatus = (typeof FILE_STATUSES)[number];

export interface CanonicalFileHeader {
  context: string;
  status: FileStatus;
  dependencies: readonly string[];
  ownership: string;
  version: string;
  limitations: readonly string[];
}

const SEMVER = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

export interface FileHeaderValidation {
  valid: boolean;
  missing: readonly string[];
  status?: FileStatus;
  version?: string;
}

/**
 * Valida el encabezado canónico. `draft | alpha | stable` únicamente.
 * Un archivo sin encabezado no cumple el gate de schema.
 */
export function validateFileHeader(header: Partial<CanonicalFileHeader>): FileHeaderValidation {
  const missing: string[] = [];
  if (!header.context?.trim()) missing.push("context");
  if (!header.status || !FILE_STATUSES.includes(header.status)) missing.push("status");
  if (!header.dependencies || header.dependencies.length === 0) missing.push("dependencies");
  if (!header.ownership?.trim()) missing.push("ownership");
  if (!header.version || !SEMVER.test(header.version)) missing.push("version");
  if (!header.limitations || header.limitations.length === 0) missing.push("limitations");
  return {
    valid: missing.length === 0,
    missing: Object.freeze(missing),
    status: header.status,
    version: header.version,
  };
}

export interface HeaderScanResult {
  /** ¿el contenido declara explícitamente su estado auto-generado? */
  declaredAutoGenerated: boolean;
  /** ¿el contenido declara aprobación humana? */
  declaredHumanApproved: boolean;
  /** estado efectivo según transparencia radical. */
  effectiveState: FileStatus | "auto_generated";
}

/**
 * Transparencia radical: un archivo generado automáticamente que no fue revisado
 * por un humano se declara `draft | auto_generated`.
 */
export function scanTransparency(content: string, declaredStatus?: FileStatus): HeaderScanResult {
  const declaredAutoGenerated = /\bstate:\s*(?:draft|auto_generated)\b/i.test(content) || /\bauto_generated\b/i.test(content);
  const declaredHumanApproved = /\bhuman[_-]?approved\b/i.test(content) || /\bhuman[_-]?authored\b/i.test(content);
  const effectiveState: FileStatus | "auto_generated" = declaredHumanApproved
    ? (declaredStatus ?? "stable")
    : declaredAutoGenerated
      ? "auto_generated"
      : (declaredStatus ?? "draft");
  return { declaredAutoGenerated, declaredHumanApproved, effectiveState };
}

/** Detecta credenciales/PII que las reglas de contribución prohíben. */
export function detectForbiddenContent(content: string): readonly string[] {
  const findings: string[] = [];
  if (/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(content)) findings.push("private_key");
  if (/\bAKIA[0-9A-Z]{16}\b/.test(content)) findings.push("aws_access_key");
  if (/\bBearer\s+[A-Za-z0-9._-]{20,}/.test(content)) findings.push("bearer_token");
  return Object.freeze(findings);
}
