use axum::{extract::{State,Request,Query},http::header::AUTHORIZATION,middleware::{self,Next},response::Response,routing::{get,post},Json,Router,http::StatusCode};
use abx::{Crown,CrownDecision};use bookpix::{BookPiEvent,BookPiLedger};use cognition::{ReasoningEngine,planner::RiskTier};use memory::MemoryRepository;use serde::{Deserialize,Serialize};use shared::{EpistemicState,MemoryRecord,MemoryScope};use sqlx::{postgres::PgPoolOptions,PgPool};use std::{env,sync::Arc};use uuid::Uuid;use sha2::Digest;
#[derive(Clone)]struct AppState{pool:PgPool,memory:MemoryRepository,ledger:BookPiLedger,api_token:String}
#[derive(Debug,Deserialize)]struct InferRequest{tenant_id:Uuid,user_id:Uuid,text:String}
#[derive(Debug,Serialize)]struct InferResponse{request_id:Uuid,trace_id:Uuid,decision:CrownDecision,plan:serde_json::Value,evidence_status:EpistemicState,execution_performed:bool}
#[derive(Debug,Deserialize)]struct CreateMemoryRequest{tenant_id:Uuid,user_id:Uuid,scope:MemoryScope,content:String,provenance:String,importance:Option<f32>,expires_at:Option<chrono::DateTime<chrono::Utc>>}
#[derive(Debug,Deserialize)]struct ListMemoryQuery{tenant_id:Uuid,user_id:Uuid,limit:Option<i64>}
#[tokio::main]async fn main()->anyhow::Result<()>{dotenvy::dotenv().ok();tracing_subscriber::fmt().with_env_filter(tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_|"info".into())).init();let database_url=env::var("DATABASE_URL")?;let api_token=env::var("IGE_API_TOKEN").map_err(|_|anyhow::anyhow!("IGE_API_TOKEN must be configured"))?;if api_token.len()<32{anyhow::bail!("IGE_API_TOKEN must contain at least 32 characters")}let pool=PgPoolOptions::new().max_connections(10).acquire_timeout(std::time::Duration::from_secs(3)).connect(&database_url).await?;sqlx::migrate!("../../migrations").run(&pool).await?;let state=Arc::new(AppState{memory:MemoryRepository::new(pool.clone()),ledger:BookPiLedger::new(pool.clone()),pool,api_token});let protected=Router::new().route("/api/v1/infer",post(infer)).route("/api/v1/memory",post(save_memory).get(list_memory)).route("/api/v1/ops/audit/verify",get(verify_audit)).route_layer(middleware::from_fn_with_state(state.clone(),authenticate));let app=Router::new().route("/health",get(health)).route("/ready",get(ready)).merge(protected).with_state(state);let bind=env::var("IGE_BIND").unwrap_or_else(|_|"0.0.0.0:8080".into());let listener=tokio::net::TcpListener::bind(&bind).await?;tracing::info!(%bind,"IGE-Ω gateway started");axum::serve(listener,app).with_graceful_shutdown(async{let _=tokio::signal::ctrl_c().await;}).await?;Ok(())}
async fn authenticate(State(s):State<Arc<AppState>>,req:Request,next:Next)->Result<Response,StatusCode>{let expected=format!("Bearer {}",s.api_token);let got=req.headers().get(AUTHORIZATION).and_then(|v|v.to_str().ok()).unwrap_or_default();if !constant_time_eq(got.as_bytes(),expected.as_bytes()){return Err(StatusCode::UNAUTHORIZED)}Ok(next.run(req).await)}
fn constant_time_eq(a:&[u8],b:&[u8])->bool{if a.len()!=b.len(){return false}a.iter().zip(b).fold(0u8,|v,(x,y)|v|(x^y))==0}
async fn health()->Json<serde_json::Value>{Json(serde_json::json!({"status":"ok","system":"IGE-OMEGA","version":"2.0.0","mode":"proposal-only"}))}
async fn ready(State(s):State<Arc<AppState>>)->Result<Json<serde_json::Value>,StatusCode>{sqlx::query("SELECT 1").execute(&s.pool).await.map_err(|_|StatusCode::SERVICE_UNAVAILABLE)?;Ok(Json(serde_json::json!({"status":"ready","database":"reachable"})))}
async fn infer(State(s):State<Arc<AppState>>,Json(input):Json<InferRequest>)->Result<Json<InferResponse>,StatusCode>{let text=input.text.trim();if text.is_empty()||text.chars().count()>12000{return Err(StatusCode::BAD_REQUEST)}let plan=ReasoningEngine::reason(text).map_err(|_|StatusCode::BAD_REQUEST)?;let human=matches!(plan.risk,RiskTier::High|RiskTier::Critical);let decision=Crown::arbitrate(true,plan.risk,human);let request_id=Uuid::now_v7();let trace_id=Uuid::now_v7();let plan_json=serde_json::to_value(&plan).map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;let payload=serde_json::json!({"tenant_id":input.tenant_id,"user_id":input.user_id,"decision":decision,"plan":plan_json});let digest=format!("{:x}",sha2::Sha256::digest(serde_json::to_vec(&payload).map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?));let event=BookPiEvent{event_id:Uuid::now_v7(),trace_id,event_type:"INFERENCE_PROPOSED".into(),world_state_hash:"UNAVAILABLE".into(),expert_set_hash:"NONE".into(),reasoning_hash:digest.clone(),outcome_hash:digest,previous_hash:String::new(),event_hash:String::new(),payload,created_at:chrono::Utc::now()};s.ledger.append(event).await.map_err(|e|{tracing::error!(error=%e,"BookPI append failed");StatusCode::INTERNAL_SERVER_ERROR})?;Ok(Json(InferResponse{request_id,trace_id,decision,plan:plan_json,evidence_status:EpistemicState::Unverified,execution_performed:false}))}
async fn save_memory(State(s):State<Arc<AppState>>,Json(input):Json<CreateMemoryRequest>)->Result<(StatusCode,Json<serde_json::Value>),StatusCode>{let content=input.content.trim();if content.is_empty()||content.chars().count()>20000||input.provenance.trim().is_empty(){return Err(StatusCode::BAD_REQUEST)}let importance=input.importance.unwrap_or(0.5);if !importance.is_finite()||!(0.0..=1.0).contains(&importance){return Err(StatusCode::BAD_REQUEST)}let record=MemoryRecord{id:Uuid::now_v7(),tenant_id:input.tenant_id,user_id:input.user_id,scope:input.scope,content:content.into(),embedding:None,importance,provenance:input.provenance,epistemic_state:EpistemicState::Unverified,created_at:chrono::Utc::now(),expires_at:input.expires_at};s.memory.insert(&record).await.map_err(|e|{tracing::error!(error=%e,"memory insert failed");StatusCode::INTERNAL_SERVER_ERROR})?;Ok((StatusCode::CREATED,Json(serde_json::json!({"stored":true,"memory_id":record.id,"epistemic_state":"UNVERIFIED"}))))}
async fn list_memory(State(s):State<Arc<AppState>>,Query(q):Query<ListMemoryQuery>)->Result<Json<serde_json::Value>,StatusCode>{let records=s.memory.list_by_user(q.tenant_id,q.user_id,q.limit.unwrap_or(20)).await.map_err(|e|{tracing::error!(error=%e,"memory read failed");StatusCode::INTERNAL_SERVER_ERROR})?;let count=records.len();Ok(Json(serde_json::json!({"records":records,"count":count})))}
async fn verify_audit(State(s):State<Arc<AppState>>)->Result<Json<serde_json::Value>,StatusCode>{let valid=s.ledger.verify().await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;Ok(Json(serde_json::json!({"valid":valid,"algorithm":"SHA-256 chained event hashes","guarantee":"tamper-evidence only; not digital signature or WORM"})))}
