import { randomUUID,createHash } from "node:crypto"; import type { EvidenceNode,EpistemicProfile,LitleAttestation,LitleId } from "./types"; import { deriveLitleId,toCanonical } from "./id"; import { buildEvidenceChain,createEvidenceNode } from "./evidence"; import { createEpistemicProfile } from "./epistemic"; import { issueCertificate,type LitleCertificate } from "./certificate";
export interface LitleAttestInput{year:number;namespace:string;workType:LitleId["workType"];container?:Uint8Array;evidence:ReadonlyArray<{id?:string;type:EvidenceNode["type"];content:string;parentIds?:readonly string[];metadata?:Readonly<Record<string,string>>}>;dimensions?:EpistemicProfile["dimensions"];aiAssisted?:boolean;}
export interface LitleAttestResult{id:LitleId;canonicalId:string;evidenceChain:ReturnType<typeof buildEvidenceChain>;profile:EpistemicProfile;attestation:LitleAttestation;certificate:LitleCertificate;}
export class LitleTrustFabric{constructor(private readonly secret:string){if(secret.length<16)throw new Error("LITLE trust fabric requires secret >= 16 chars");}
attest(input:LitleAttestInput):LitleAttestResult{
if(!input||!Array.isArray(input.evidence)||input.evidence.length===0||input.evidence.length>100)throw new Error("LITLE evidence count must be between 1 and 100");
if(!Number.isInteger(input.year)||input.year<1900||input.year>9999)throw new Error("LITLE invalid year");
if(typeof input.namespace!=="string"||input.namespace.length>64)throw new Error("LITLE invalid namespace");
if(input.container!==undefined&&(!(input.container instanceof Uint8Array)||input.container.length>1_000_000))throw new Error("LITLE container must be <= 1MB of bytes");
const totalEvidenceChars=input.evidence.reduce((total,item)=>total+(typeof item?.content==="string"?item.content.length:1_000_001),0);
if(totalEvidenceChars>1_000_000)throw new Error("LITLE evidence content exceeds 1MB");
const source=input.container??new TextEncoder().encode(input.evidence.map(e=>e.content).join("\n"));const container=this.normalizeContainer(source);const id=deriveLitleId({containerBytes:container,year:input.year,namespace:input.namespace,workType:input.workType});const nodes=input.evidence.map((e,i)=>createEvidenceNode({id:e.id??("node-"+(i+1)+"-"+randomUUID().slice(0,8)),type:e.type,content:e.content,parentIds:e.parentIds,metadata:e.metadata}));const evidenceChain=buildEvidenceChain(nodes);const profile=createEpistemicProfile({litleId:toCanonical(id),dimensions:input.dimensions,aiAssisted:input.aiAssisted,hasEvidenceChain:true,hasCryptoSignature:true});const certificate=issueCertificate({id,evidenceRoot:evidenceChain.rootHash,profile,secret:this.secret});return {id,canonicalId:toCanonical(id),evidenceChain,profile,certificate,attestation:{litleId:id,canonicalId:toCanonical(id),evidenceRoot:evidenceChain.rootHash,epistemicScore:profile.compositeScore,qualityTier:certificate.qualityTier,attestedAt:certificate.issuedAt,verifier:"genesisai-litle-fabric",cryptographicBinding:createHash("sha256").update(certificate.signature).digest("hex")}};}
private normalizeContainer(input:Uint8Array):Uint8Array{if(input.length===512)return new Uint8Array(input);const out=new Uint8Array(512);out.set(input.slice(0,512));const digest=createHash("sha3-512").update(input).digest();out.set(digest,512-digest.length);return out;}}