use chrono::{DateTime,Utc};
use serde_json::Value;
use shared::{EpistemicState,IgeError,IgeResult,MemoryRecord,MemoryScope};
use sqlx::{PgPool,Postgres,Row,Transaction};
use uuid::Uuid;
#[derive(Clone)]pub struct MemoryRepository{pool:PgPool}
impl MemoryRepository{pub fn new(pool:PgPool)->Self{Self{pool}}pub async fn insert(&self,r:&MemoryRecord)->IgeResult<()>{let mut tx=self.pool.begin().await.map_err(db)?;self.insert_in_transaction(&mut tx,r).await?;tx.commit().await.map_err(db)?;Ok(())}pub async fn insert_in_transaction(&self,tx:&mut Transaction<'_,Postgres>,r:&MemoryRecord)->IgeResult<()>{let embedding=r.embedding.as_ref().map(serde_json::to_value).transpose().map_err(|e|IgeError::InvalidInput(e.to_string()))?;sqlx::query("INSERT INTO memory_records(id,tenant_id,user_id,scope,session_id,content,embedding,importance,provenance,epistemic_state,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)").bind(r.id).bind(r.tenant_id).bind(r.user_id).bind(r.scope.as_str()).bind(r.session_id).bind(&r.content).bind(embedding).bind(r.importance).bind(&r.provenance).bind(r.epistemic_state.as_str()).bind(&r.created_at).bind(&r.expires_at).execute(&mut **tx).await.map_err(db)?;Ok(())}pub async fn delete_in_transaction(&self,tx:&mut sqlx::Transaction<'_,sqlx::Postgres>,tenant:Uuid,user:Uuid,id:Uuid)->IgeResult<bool>{let deleted=sqlx::query("DELETE FROM memory_records WHERE id=$1 AND tenant_id=$2 AND user_id=$3 RETURNING id").bind(id).bind(tenant).bind(user).fetch_optional(&mut **tx).await.map_err(db)?;Ok(deleted.is_some())}pub async fn list_by_user(&self,tenant:Uuid,user:Uuid,limit:i64,session_id:Option<Uuid>)->IgeResult<Vec<MemoryRecord>>{let rows=sqlx::query("SELECT id,tenant_id,user_id,scope,session_id,content,embedding,importance,provenance,epistemic_state,created_at,expires_at FROM memory_records WHERE tenant_id=$1 AND (scope='TENANT' OR (scope='USER' AND user_id=$2) OR (scope='SESSION' AND user_id=$2 AND session_id=$4)) AND (expires_at IS NULL OR expires_at>NOW()) ORDER BY created_at DESC LIMIT $3").bind(tenant).bind(user).bind(limit.clamp(1,100)).bind(session_id).fetch_all(&self.pool).await.map_err(db)?;rows.into_iter().map(|r|{let scope:String=r.try_get("scope").map_err(db)?;let epi:String=r.try_get("epistemic_state").map_err(db)?;let embedding:Option<Value>=r.try_get("embedding").map_err(db)?;let embedding=embedding.map(serde_json::from_value::<Vec<f32>>).transpose().map_err(|e|IgeError::Database(e.to_string()))?;Ok(MemoryRecord{id:r.try_get("id").map_err(db)?,tenant_id:r.try_get("tenant_id").map_err(db)?,user_id:r.try_get("user_id").map_err(db)?,scope:parse_scope(&scope)?,session_id:r.try_get("session_id").map_err(db)?,content:r.try_get("content").map_err(db)?,embedding,importance:r.try_get("importance").map_err(db)?,provenance:r.try_get("provenance").map_err(db)?,epistemic_state:parse_epi(&epi)?,created_at:r.try_get::<DateTime<Utc>,_>("created_at").map_err(db)?,expires_at:r.try_get("expires_at").map_err(db)?})}).collect()}}
fn db(e:sqlx::Error)->IgeError{IgeError::Database(e.to_string())}
fn parse_scope(s:&str)->IgeResult<MemoryScope>{match s{"TENANT"=>Ok(MemoryScope::Tenant),"USER"=>Ok(MemoryScope::User),"SESSION"=>Ok(MemoryScope::Session),_=>Err(IgeError::Database("unknown memory scope".into()))}}
fn parse_epi(s:&str)->IgeResult<EpistemicState>{match s{"UNVERIFIED"=>Ok(EpistemicState::Unverified),"SOURCE_FOUND"=>Ok(EpistemicState::SourceFound),"CORROBORATED"=>Ok(EpistemicState::Corroborated),"ACADEMICALLY_SUPPORTED"=>Ok(EpistemicState::AcademicallySupported),"REPRODUCIBLE"=>Ok(EpistemicState::Reproducible),"VALIDATED"=>Ok(EpistemicState::Validated),"ESTABLISHED"=>Ok(EpistemicState::Established),"DISPUTED"=>Ok(EpistemicState::Disputed),"REJECTED"=>Ok(EpistemicState::Rejected),"DEPRECATED"=>Ok(EpistemicState::Deprecated),_=>Err(IgeError::Database("unknown epistemic state".into()))}}
